services:
  mongo:
    image: mongo:8.0
    container_name: edc_mongo
    volumes:
      - mongo_data:/data/db
    networks:
      - edc_network

  postgres:
    image: postgres:15
    container_name: edc_postgres
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - edc_network

  backend:
    image: agrixelsupc/edc_studio_backend:latest
    container_name: edc_backend
    platform: linux/amd64
    ports:
      - "8000:8000"
    environment:
      MONGODB_URI: ${MONGODB_URI}
      MONGODB_DB: ${MONGODB_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASS: ${POSTGRES_PASSWORD}
      POSTGRES_HOST: ${POSTGRES_HOST}
      POSTGRES_PORT: ${POSTGRES_PORT}
      RUNTIME_PATH: ${RUNTIME_PATH}
      NETWORK_NAME: ${NETWORK_NAME}
      TYPE: ${TYPE}
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./runtime:/app/runtime
    depends_on:
      - mongo
    networks:
      - edc_network

  frontend:
    image: agrixelsupc/edc_studio:latest
    container_name: edc_studio
    platform: linux/amd64
    ports:
      - "3000:3000"
    depends_on:
      - backend
    volumes:
      - .env.frontend:/usr/share/nginx/html/assets/assets/.env
    networks:
      - edc_network

volumes:
  mongo_data:
  postgres_data:

networks:
  edc_network:
    external: true